-- Insert blogs with specific categories for LAKUM Artspace

INSERT INTO blogs (title, excerpt, content, author, category, cover_image, created_at) VALUES
('The Art of Contemporary Expression', 'Exploring modern artistic movements and their impact on Saudi culture', 'Contemporary art has undergone significant transformations over the past decades, reflecting the evolving values and perspectives of society. In this article, we explore how modern artistic movements have shaped cultural discourse and influenced creative expression worldwide.', 'LAKUM Team', 'Art & Culture', 'assest/img-3.JPG', '2025-12-16'),
('Behind the Scenes: Curating an Exhibition', 'A look into the meticulous process of bringing art to life', 'Curating an exhibition is a complex and rewarding process that requires careful planning, artistic vision, and attention to detail. From selecting artworks to designing the gallery layout, every element plays a crucial role in creating a memorable experience for visitors.', 'Sarah Al-Mansour', 'Behind the Scenes', 'assest/img-4.png', '2025-12-16'),
('LAKUM Impact on Local Artists', 'How our space has become a catalyst for artistic growth', 'LAKUM Artspace has become a vibrant hub for local artists, providing them with the resources, platform, and community support they need to thrive. Through exhibitions, workshops, and collaborative projects, we continue to foster artistic growth and cultural exchange.', 'Mohammed Al-Rashid', 'Community', 'assest/img-3.JPG', '2025-12-16'),
('Photography Tips for Beginners', 'Essential photography techniques to help you capture stunning images', 'Photography is an art form that requires practice and understanding of fundamental principles. In this tutorial, we cover essential techniques including composition, lighting, and post-processing to help you capture stunning images.', 'Michael Chen', 'Tutorial', 'assest/img-4.png', '2025-12-15'),
('Digital Art Tools and Software', 'A comprehensive guide to the best digital art tools available', 'The digital art landscape has evolved dramatically with new tools and software emerging constantly. This guide explores the most popular and effective digital art tools available today, helping artists choose the right software for their creative needs.', 'Emma Rodriguez', 'Exhibition', 'assest/img-3.JPG', '2025-12-15'),
('Sculpture Materials and Techniques', 'Explore different materials and techniques used in modern sculpture', 'Sculpture is one of the oldest art forms, and modern sculptors continue to push boundaries with innovative materials and techniques. From traditional stone and clay to contemporary mixed media, explore the diverse approaches to sculptural art.', 'David Martinez', 'Art & Culture', 'assest/img-4.png', '2025-12-14'),
('Building Your Art Portfolio', 'Tips and strategies for creating a compelling art portfolio', 'Your art portfolio is your professional calling card. In this article, we provide practical tips and strategies for building a compelling portfolio that showcases your best work and attracts opportunities in the art world.', 'Lisa Thompson', 'Tutorial', 'assest/img-3.JPG', '2025-12-14'),
('Latest Exhibition Highlights', 'Discover the most talked-about artworks from our recent exhibitions', 'Our recent exhibitions have featured groundbreaking works from both established and emerging artists. This article highlights the most impactful pieces and explores the themes that resonated with our visitors.', 'LAKUM Team', 'Exhibition', 'assest/img-4.png', '2025-12-13'),
('Art News: Global Trends', 'Stay updated with the latest developments in the art world', 'The global art scene continues to evolve with new movements, technologies, and perspectives shaping contemporary practice. Stay informed about the latest trends and developments that are influencing artists worldwide.', 'James Wilson', 'News', 'assest/img-3.JPG', '2025-12-13'),
('Community Spotlight: Local Artists', 'Celebrating the talented artists in our community', 'Our community is home to incredibly talented artists working across various mediums and styles. In this spotlight, we celebrate their contributions and explore what drives their creative practice.', 'Fatima Al-Dosari', 'Community', 'assest/img-4.png', '2025-12-12');
